MacOSX port: Tweak flags in Makefile. Rework .h's to move compilation along.
- Gentle introduction of libuv.h into code base
- Rework some includes to avoid make errors.

- Builds are still succeeding on Linux.

Things move along but we are now stuck on core IO interfaces:

cc -MMD -MT obj/src/rc_allocator.o -MP -MF obj/src/rc_allocator.d -D_GNU_SOURCE -Wall -Wfatal-errors -msse4.2 -mpopcnt -DXXH_STATIC_LINKING_ONLY -fPIC -I/usr/local/Cellar/libconfig/1.7.3/include -Ofast -flto -march=native -I src -I src/platform_macOSX -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -arch x86_64 -c src/rc_allocator.c -o obj/src/rc_allocator.o

In file included from src/rc_allocator.c:10:
In file included from src/platform_macOSX/platform.h:558:
In file included from src/platform_macOSX/platform_inline.h:7:
src/platform_macOSX/laio.h:19:21: fatal error: field has incomplete type 'struct iocb'
    struct iocb     iocb;        // laio callback
                    ^
src/platform_macOSX/laio.h:19:12: note: forward declaration of 'struct iocb'
    struct iocb     iocb;        // laio callback
           ^
1 error generated.

Revert change in linux #include -> laio.h