MacOSX port: Initial changes to get compilation going.
This commit introduces very initial changes to rearrange
defines in Makefile to enable compilation to proceed on
Mac/OSX platform.

- Conditionalized various symbols off of PLATFORM symbol
- Provide extra flags, args, -I include-dirs for Mac
- Builds continue to work on Linux, but fail on Mac while
  trying to locate, e.g., definition of FILE:

  src/platform_macOSX/platform_types.h:55:9: fatal error: unknown type name 'FILE'