Core changes to support running Splinter with allocated shared memory.
This commit brings in basic support to create a shared memory segment and
to redirect all memory allocation primitives to shared memory. Currently,
we only support a simplistic memory mgmt; i.e. only-allocs, and no frees.
With shared segments of 1-2 GiB we can run many functional and unit
tests.

Some cavaets and fixes implemented to get some tests to run cleanly:

o Redirect large allocations to use malloc(), and not the shmem allocation.

  We currently do not support free() for shared memory based allocation.
  Some sub-systems that allocate and free large chunks repeatedly use
  up too much shared memory, causing tests to fail  .

  This commit fixes that issue by re-directing following clients to
  fall-back to using regular malloc() / free() interfaces:

  - merge_iterator_create()
  - merge_iterator_destroy(),
  - trunk_range() - trunk_range_iterator
  - trunk_range_iterator_deinit()
  - btree_pack_req_init()
  - btree_pack_req_deinit()

  With these changes, unit-test splinter_test now succeeds using shared memory:

sdb-fdb-build:[10] $ build/debug/bin/unit/splinter_test
Running 1 CTests, suite name 'splinter', test case 'all'.
TEST 1/3 splinter:test_inserts [OK]
TEST 2/3 splinter:test_lookups [OK]
TEST 3/3 splinter:test_splinter_print_diags [OK]
RESULTS: 3 tests (3 ok, 0 failed, 0 skipped) ran in 1136485 ms

o Rework existing tests to support --use-shmem arg to run w/ shared segment.

  Apply --use-shmem as the very 1st arg for different tests so that they
  can now leverage shared memory support. Following tests are / should be
  working with this fix:

 - limitations_test
 - splinterdb_quick_test
 - writable_buffer_test
 - task_system_test
 - splinter_test
 - btree_test

With this argument, splinterdb_create_or_open() will now create a heap,
i.e., allocate shared segment, if the calling test has not already done so.

NOTE: unit/btree_test still goes through shm-free code due to the use
      of scratch_buffer space in this test masquerading as heap-id.
      Investigate and resolve.

o Fix bugs & refactoring to enable unit stress-tests.

  Minor rearrangement of code and fixing bugs. This commit now
  enables running btree_test and splinterdb_stress_test unit-tests
  with --use-shmem option.

o Enhances memory alloc/free diags to print name of object.

  To better understand for which object memory allocation
  or free is occurring, this commit makes minor changes to
  caller-macros that allocate / free memory to
  also print object's name using STRINGIFY() on the parameter 'v'.

o Rework unit-testing, main.c, Makefile to support --use-shmem

  Change test.sh also to run unit-tests with --use-shmem

Fix build failures, shfmt issues and chmod +x test.sh issues.

Fix chmod perms to +x

Enable use of shared-memory for all core Splinter functionality & tests.

This commits introduces several changes on top of the core shared memory support
to stabilize this feature. With this commit we are able to cleanly run
all unit, functional and performance tests that are invoked in CI-runs with
shared-memory enabled. (Tests consistently use --use-shmem option.)

High-level description of changes implemented:

- Document heavily in multiple places that support for shared-memory
  segments is an EXPERIMENTAL feature.

- Add spinlock-based concurrency control for memory allocation, realloc
  and free from shared-memory. Add multi-threaded unit-test to validate
  that things would break w/o this fix.

- Manage handling of heap-ID and heap-handle to platform_get_heap_id() to
  correctly return the handle to shared memory. (Otherwise, it would return
  NULL by default.)

- Formalize usages of PROCESS_PRIVATE_HEAP_ID: A small number of clients that
  wish to repeatedly allocate large chunks of memory tend to cause OOMs. The
  memory allocated by these clients is not shared across threads / processes.
  For such usages, introduce PROCESS_PRIVATE_HEAP_ID as an alias to NULL.
  The known set of clients using this interface now are:

    - merge_iterator_create(), routing_filter_add(), trunk_range()

- BTree pack allocates large fingerprint-array. This also causes large tests
  to run into OOMs. For threaded execution, it's ok if the memory for this
  array is allocated from the heap. But for multi-process execution, when one
  process (thread) allocates this finger print array, another thread may pick
  up the task to compact a bundle and will try to free this memory. So, this
  memory has to come from shared memory. To cope with such repeated allocations
  of large chunks of memory to build fingerprint, a small recycling scheme for
  "free"-large-memory chunks scheme is now supported.

  Use this technique to recycle memory allocated for iterators also. They tend
  to be big'gish, so can also cause shmem-OOMs.

- Address requirements from writable_buffer_append() -> writable_buffer_resize()
  which invokes 'realloc' on shared-memory side. Fix bugs in platform_shm_realloc()
  which was not copying over 'oldptr' contents previously.

- Tighten checks for failure to allocate memory and improve backout handling
  in a few places.

- Add shared memory usage metrics, including for large-fragment handling. Report
  summary-line of metrics when Splinter is shutdown. Print stats on close.

- Add various utility diagnostic helper methods to validate that addresses
  within shared memory are valid. Unit-tests and some asserts use these.

- Add tracing support to trace through shared memory allocation, free.
  Add globals to splinterdb_config{} to track these boolean trace flags.
  Add cmdline args: --trace-shmem, --trace-shmem-allocs, --trace-shmem-frees

Support recycling of memory allocated for iterators. Print stats on close.
Pull-in test_free_realloc_around_inuse_fragments() test case.

- Reduce SHM_LARGE_FRAG_SIZE from 90KiB to 38 KiB. This allows using the
  free-fragment recycling for memory chunks allocated for iterators also.
  [Otherwise, running large # of queries, each of which opens an
  iterator, will cause OOM in shared segment.]

- Call splinterdb_stats_print_insertion() under splinterdb_close_print_stats()
  so we get stats printed when SplinterDB is closed.

Commit fix.

Track metrics & diagnostics for free-fragments tracking strategy.

Track metrics for free-fragment search optimization.
Trace list of large fragments tracked when SplinterDB shuts down.

We are running into shmem-OOM while allocating large fragments. It's
puzzling why the scheme seems to work, in general, but we are still
over-allocating shared memory for large fragments.

This commit adds diagnostic code to trace the set of large fragments
[still] tracked in the shmem control block. Provide a new global,
Trace_large_frags, and helper methods to turn this ON.

With this infrastructure, when we run large-inserts workloads through
Pg-integration, we do see some large fragments still "in-use" when
Splinter is shut down. This indicates some form of memory leak.

At shutdown time, add diagnostic function to check if any free-fragments
are still left in-use.

Cleanup diags, asserts and tracking of large-free fragments handling.
Fixes to ensure we destroy heap in all error code flows when
splinterdb_create() exits due to bad config parameters.
Otherwise, some cases in limitations_test would end up not destroying
the heap, which leaves shared segments around.

(#457) Productize stress test to exercise large #s of inserts

This commit adds a stress test to exercise large #s of inserts,
from a main connection to Splinter, or from multiple threads.
Some test-configuration is provided
  o --num-inserts; default 20 Million
  o --num-threads default 8, each thread inserts --num-insert KV-pairs

All combinations of seq/random keys/value-pairs are supported.
Currently, no new bugs were discovered with this test.

Usage: ./unit/large_inserts_bugs_stress_test
              [--num-inserts <x-Millions>]
              [--num-threads 10]
              [--verbose-progress]

- Support --use-shmem arg to run this new test.
- Stabilize cases in large_inserts_bugs_stress_test. One skipped.
- Include large_inserts_stress_test with --use-shmem in nightly stress tests
- Increase dev-size in large inserts stress test to 40GiB for successful run.
- Rework large_inserts_bugs_stress test to generate assertion failure.

This commit slightly enhances do_inserts_n_threads() in this
test case to cajole an assertion seen from BTree split code, or
thereabouts:

OS-pid=1839020, Thread-ID=5, Assertion failed at src/trunk.c:5521:trunk_split_leaf(): "(num_leaves + trunk_num_pivot_keys(spl, parent) <= spl->cfg.max_pivot_keys)". num_leaves=6, trunk_num_pivot_keys()=9, cfg.max_pivot_keys=14

The changes are:
 - Provide options to use same / diff start-key for each thread.
 - Increase TEST_KEY_SIZE to 30 and TEST_VALUE_SIZE to 256 bytes.
 - Provide an option to either generate sequential values or to
   use fully-packed values for each key. The latter seems to be
   the condition that triggers this assertion.

Many diff variations of test cases are provided in this one large
framework. See large_inserts_bugs_stress_test --list for names of
individual test cases.

Changes to run large insert stress tests with 63 threads.

We are seeing assertions in PG-integrated Splinter code when we
have more than, say, 50 or so concurrent psql clients firing
inserts. Assertion in laio.c to do with IO-context indexed
by 'tid' is failing:

OS-pid=1897373, Thread-ID=18446744073709551615, Assertion failed at src/platform_linux/laio.c:109:io_context_setup(): "(io->ctx[tid] == NULL)". ThreadID=18446744073709551615, ctx[tid]=0x7ffab9d7088    8

The assertion is valid, but the 'tid' reported seems to be a wrong
number. We expect this to be in the range of [0-63]. Somehow this
reeks of an uninitialized threadid variable.

This commit tries to repro this assertion, using existing unit tests.
But the attempts were unsuccessful. Some changes were needed in
configuration to run with --num-threads 63.

- Fix some off-by-1 checks in clockcache.c, around use of MAX_THREADS.
- Add field shm_large_frag_hip in shm-control block to track the
  highest-start address of large fragments that are being tracked.
  This is a light-weight optimization to reduce the # of searches
  thru the array where any generic memory fragment is freed.

With these changes, following ran successfully, and could not repro
above assertion:

$ large_inserts_bugs_stress_test --use-shmem --num-inserts 1000000 --num-threads 63 test_seq_key_seq_values_inserts_threaded

--
Fixes to stabilize large_inserts stress test. Suppress noisy trace messages

This commit fixes small bugs that were preventing all test cases in
large inserts stress test to run cleanly. We are now able to run this cleanly
as part of run_tests_with_shared_memory() test-execution method.

Make shared memory size a configuration parameter; Initial support

Introduce shmem_size in master_config{} and splinterdb_config{}
structures. Default remains at 2 GiB. Extend large_inserts_stress_test
to pass-down 4GiB to splinterdb_create(), to create larger shared segment.

(More work is pending to make this a command-line arg.)

Enable use of background threads in Splinter. Engage tests.

This commit exercises use of background threads, a feature that
has been implemented and stabilized in /main previously.

Enhanced config_parse() to recognize these two new options.
Added a case to test.sh to exercise the task_system_test with
background threads.

Support --shmem-capacity-mib, --shmem-capacity-gib options.
Enable bg-threads in tests.

Collection of bug-fixes, test-enablement fixes. No new functionality

This commit ports a miscellany of changes from the POC-dev branch.

- Add splinter_shmem:test_allocations_causing_OOMs() sub-case
  Discovers and fixes an off-by-one end-of-shmem addr bug.
- Print message that OOM-errors are expected.
- Enable running io_apis_test with --use-shmem option. Found and fixed
  minor memory leaks, which were discovered by shmem diagnostics.
- Include that test in test.sh/run_fast_unit_tests()
- Improve couple of assert / error messages

--
Rework mgmt of heap_id, heap_handle to work correctly in all backout paths.

This commit fixes backout / memory release issues in splinterdb_create_or_open()
encountered in unit-tests run with --use-shmem that trigger error conditions.
We have to use the correct heap_handle to destroy the heap in all exit code
paths

--
Refactor shm-related Trace globals, to avoid ASAN complaints in unit tests.

Rather than defining them as global, make them static to shmem.c and
externalize existing accessor method. splinterdb.c is changed to not
deal with globals, but calls setter method.

--
Fix build issues to redefinition of bool on /main